salario = float(input('Qual é o salario do Funcionario? R$'))
novo = salario + (salario*15/100)
print('Um funcionário que ganhava R${:.2f}, com 15% de aumento, passa a receber R${:.2f}.'.format(salario, novo))
salario = float(input('qual é o seu salário? R$'))
novo = salario + (salario*15/100)
print('o funcionário que ganhava R${}, com o aumento de 15%, passa a ganhar R${}.'.format(salario, novo))